"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#ff8b39)\
$os\
$username\
[](bg:#ff8b39 fg:#ff8b39)\
$directory\
[](fg:#ff8b39 bg:#fede5d)\
$git_branch\
$git_status\
[](fg:#fede5d bg:#ff7edb)\
$nodejs\
$python\
[](fg:#ff7edb bg:#169FFF)\
$docker_context\
[](fg:#169FFF bg:#36f9f6)\
$time\
[ ](fg:#36f9f6)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#ff8b39"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
symbol = " "
style = "bg:#ff7edb"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#fede5d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#fede5d"
format = '[$all_status$ahead_behind ]($style)'


[nodejs]
symbol = "󰎙"
style = "bg:#ff7edb"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#ff7edb"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#36f9f6"
format = '[ ♥ $time ]($style)'
